#!/usr/bin/bash

# Must be used after copying the env file into the tmp folder
set_env() {
  # Usage: set_env 'ENV_VARIABLE="value"' -> Adds the env variable to the envs file on the tmp folder and leaves the placeholder
  # Usage: set_env '' -> Removes the placeholder
  if [[ -z $1 ]]; then
    expr="\n"
  else
    export $1
    expr="$1\n{AUTOGENERATED}"
  fi
  sed -i "s|{AUTOGENERATED}|$expr|" "$tmp/env"
}

tmp="/tmp/dotfiles"
mkdir -p "$tmp"

if [[ -z $DOTFILES ]]; then
  DOTFILES="$HOME/dotfiles"
  echo "Env variable DOTFILES not found..."
  echo "Files will be stored in '$DOTFILES' directory."

  read -p "You want to continue? y/n" -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]?$ ]]; then
    echo "Canceled..."
    exit 0
  fi
  clear
fi

if [[ ! -d "$DOTFILES" ]]; then
  git clone https://github.com/aaron70/dotfiles -b archlinux/terminal $DOTFILES
  clear
fi

INSTALLATION_SCRIPTS="$DOTFILES/scripts/installation"
cp $INSTALLATION_SCRIPTS/env $tmp/env

set_env "DOTFILES=$DOTFILES"
set_env "INSTALLATION_SCRIPTS=$INSTALLATION_SCRIPTS"

set_env "" # Removes the placeholder for ad ing more env variables

sudo bash -c "cat $tmp/env >> /etc/environment"

source /etc/environment
$INSTALLATION_SCRIPTS/apply.sh

#echo "Setup completed!"
#echo "Run the following commands to apply the dotfiles configuration:"
#echo ""
#echo "source /etc/environment"
#echo "$INSTALLATION_SCRIPTS/apply.sh"

